### ISSUE TITLE
Exception raised

### ISSUE THREAD

**Issue by metalshark** [miniaturepets/issues#167]
Sorry I've got nothing more to go on here. No idea what caused it and it's so rare this is the first time we've seen it on an active server. Version 2.3.8 and Paper version git-Paper-162 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT).

```
java.util.NoSuchElementException: packet_handler
at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1119)
at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:260)
at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:249)
at com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:66)
at com.comphenix.protocol.injector.netty.ChannelInjector$3$1.addBefore(ChannelInjector.java:283)
at com.kirelcodes.miniaturepets.packetListeners.PacketInjector.addPlayer(PacketInjector.java:38)
at com.kirelcodes.miniaturepets.listener.CoreListener.onPlayerJoin(CoreListener.java:636)
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor296.execute(Unknown Source)
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
at net.minecraft.server.v1_15_R1.PlayerList.a(PlayerList.java:192)
at net.minecraft.server.v1_15_R1.LoginListener.c(LoginListener.java:174)
at net.minecraft.server.v1_15_R1.LoginListener.tick(LoginListener.java:65)
at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:256)
at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:139)
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1269)
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
```

**Comment by danielnaaman** [comment]
That's odd, I'll prioritize this. Could you clarify what caused it? Or perhaps add a few log lines beyond what you provided?

**Comment by liorsl** [comment]
Hello,
Could it be that the client that raised this error is using the mod inventory tweeks, or that the mod is installed on the server?

**Comment by metalshark** [comment]
I've rolled back a couple of minutes before and show log entries after too:
![log](https://user-images.githubusercontent.com/146708/78634462-f130e980-789b-11ea-84e2-842529b52010.png)

**Comment by metalshark** [comment]
> Hello,
> Could it be that the client that raised this error is using the mod inventory tweaks, or that the mod is installed on the server?

No inventory tweaks or mods for inventory tweaking added. This just looks like an exception with the client disconnecting straight after they've connected and the packet injector not hooking on fully. Only know my way around ProtocolLib and not doing it directly.

**Comment by liorsl** [comment]
And do you know for certain that the client that is disconnected have no mods installed?

**Comment by metalshark** [comment]
This client was vanilla, however, I cannot guarantee others logged on were not using modded clients.

**Comment by liorsl** [comment]
Could you make sure protocollib is the latest one for your version?

**Comment by metalshark** [comment]
Am running 4.5.0 and it auto updates with a reboot about once a day.

**Comment by NacOJerk** [comment]
Hey this seems very weird, the error is basicly saying that a certain field does not exists.

If it is rare it means that sometimes our code doesnt find it.

I have seen it once or twice but only when I have performed a wrong reload or something, can you send us the logs before this error?

**Comment by danielnaaman** [comment]
Hi,

Just to clarify, this is still an issue. Correct?

Daniel.

**Comment by metalshark** [comment]
@danielnaaman it’s still only happened the once.

**Comment by danielnaaman** [comment]
> @danielnaaman it’s still only happened the once. Also no reloads, not even per-plugin reloads.

Just to be clear, you are saying it only happened once?

**Comment by metalshark** [comment]
Yes

**Comment by danielnaaman** [comment]
> Yes

In that case unless you'll ever see it again it's sounds impossible to debug so I'll close this for now, feel free to let me know if there's anything I'm not looking at, I'd love to reopen this if this issue persists.
