### ISSUE TITLE
Mysql related error in console

### ISSUE THREAD

**Issue by Govindass** [miniaturepets/issues#173]
# Bug Report

### Technical Information
* Server Software: 1.12.2 paper
* Plugin Version:  2.3.8

### General Information

**Bug Description**
Error in console, related to mysql 

**Instructions To Produce**
I don't know what caused it, most likely pet names

**Logs**
```
[11:56:33 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-8 varchar(255)' at line 1
[11:56:33 WARN]:        at jdk.internal.reflect.GeneratedConstructorAccessor590.newInstance(Unknown Source)
[11:56:33 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[11:56:33 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
[11:56:33 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[11:56:33 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:408)
[11:56:33 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[11:56:33 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
[11:56:33 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[11:56:33 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[11:56:33 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[11:56:33 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2480)
[11:56:33 WARN]:        at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1552)
[11:56:33 WARN]:        at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2607)
[11:56:33 WARN]:        at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1480)
[11:56:33 WARN]:        at com.kirelcodes.miniaturepets.data.adapters.SQLDataManager.setPlayerData(SQLDataManager.java:169)
[11:56:33 WARN]:        at com.kirelcodes.miniaturepets.data.adapters.SQLDataManager.setPlayerString(SQLDataManager.java:85)
[11:56:33 WARN]:        at com.kirelcodes.miniaturepets.MiniaturePets.savePetName(MiniaturePets.java:254)
[11:56:33 WARN]:        at com.kirelcodes.miniaturepets.pets.Pet.setCustomName(Pet.java:475)
[11:56:33 WARN]:        at com.kirelcodes.miniaturepets.pets.Pet.<init>(Pet.java:153)
[11:56:33 WARN]:        at com.kirelcodes.miniaturepets.pets.PetContainer.spawnPet(PetContainer.java:231)
[11:56:33 WARN]:        at com.kirelcodes.miniaturepets.pets.PetContainer.spawnPet(PetContainer.java:220)
[11:56:33 WARN]:        at com.kirelcodes.miniaturepets.commands.CommandLoader$3.executeCommand(CommandLoader.java:328)
[11:56:33 WARN]:        at com.kirelcodes.miniaturepets.commands.CommandManager.executeCommand(CommandManager.java:115)
[11:56:33 WARN]:        at com.kirelcodes.miniaturepets.commands.MajorCommand.execute(MajorCommand.java:233)
[11:56:33 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[11:56:33 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[11:56:33 WARN]:        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:607)
```

**Comment by danielnaaman** [comment]
Hi, what makes you so sure that this error is related to Miniature Pets?

**Comment by Govindass** [comment]
> 
> 
> Hi, what makes you so sure that this error is related to Miniature Pets?

MiniaturePets in the stacktrace

**Comment by danielnaaman** [comment]
> > Hi, what makes you so sure that this error is related to Miniature Pets?
> 
> MiniaturePets in the stacktrace, miniaturepets also had multiple issues related to mysql in the past

Ah, correct.

Sorry about that.

Issue approved.

**Comment by liorsl** [comment]
Are you running of a shared hosting environment, or do you have a VPS or a dedicated server?

**Comment by Govindass** [comment]
> 
> 
> Are you running of a shared hosting environment, or do you have a VPS or a dedicated server?

it's VPS

**Comment by liorsl** [comment]
Try to update your MySQL server.

**Comment by Govindass** [comment]
> 
> 
> Try to update your MySQL server.

to what version? I am using

mysql  Ver 15.1 Distrib 10.1.44-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by liorsl** [comment]
Latest version, it is not updated.

**Comment by Govindass** [comment]
well this is what Debian 9 OS comes with, I'll look for a way to upgrade it separately

**Comment by danielnaaman** [comment]
> well this is what Debian 9 OS comes with, I'll look for a way to upgrade it separately

No Debian based distribution should come with any MySQL server pre-installed.

If upgrading the MySQL server doesn't resolve your issue, please let us know.

**Comment by Govindass** [comment]
> 
> 
> > well this is what Debian 9 OS comes with, I'll look for a way to upgrade it separately
> 
> No Debian based distribution should come with any MySQL server pre-installed.
> 
> If upgrading the MySQL server doesn't resolve your issue, please let us know.

I mean apt-get install mariadb-server is what it defaults to in my OS

**Comment by danielnaaman** [comment]
> > > well this is what Debian 9 OS comes with, I'll look for a way to upgrade it separately
> > 
> > 
> > No Debian based distribution should come with any MySQL server pre-installed.
> > If upgrading the MySQL server doesn't resolve your issue, please let us know.
> 
> I mean apt-get install mariadb-server is what it defaults to in my OS

Makes more sense, try to update your system by running `sudo apt-get update && sudo apt-get upgrade`.

Let me know how it works out for you.

**Comment by danielnaaman** [comment]
Issue closed due to lack of comment, I presume it's resolved. If not, please comment or DM me on Discord to reopen.
