### ISSUE TITLE
UncheckedExecutionException

### ISSUE THREAD

**Issue by metalshark** [miniaturepets/issues#184]
# Bug Report

### Technical Information
* Server Software: Paper version git-Paper-284 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
* Plugin Version:  2.4.1
* Dump File: https://pastebin.com/jXrcTghL

### General Information

**Bug Description**
Lots of errors on startup all of a sudden.

**Logs**
```
Enabling MiniaturePets v2.4.1*
Loading reflections.
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Name and ID cannot both be blank
at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
at net.minecraft.server.v1_15_R1.TileEntitySkull$3.call(TileEntitySkull.java:218)
at net.minecraft.server.v1_15_R1.TileEntitySkull$3.call(TileEntitySkull.java:215)
at net.minecraft.server.v1_15_R1.TileEntitySkull.b(TileEntitySkull.java:234)
at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftMetaSkull.applyToItem(CraftMetaSkull.java:88)
at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:518)
at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:42)
at com.kirelcodes.miniaturepets.utils.NMSClassInteracter.asNMSCopy(NMSClassInteracter.java:125)
at com.kirelcodes.miniaturepets.utils.ItemStackUtils.getSkullFromURL(ItemStackUtils.java:103)
at com.kirelcodes.miniaturepets.loader.ItemLoader.loadItem(ItemLoader.java:126)
at com.kirelcodes.miniaturepets.loader.ItemLoader.<init>(ItemLoader.java:36)
at com.kirelcodes.miniaturepets.loader.files.PetFile.<init>(PetFile.java:29)
at com.kirelcodes.miniaturepets.loader.PetLoader.registerFromFile(PetLoader.java:84)
at com.kirelcodes.miniaturepets.loader.PetLoader.<init>(PetLoader.java:47)
at com.kirelcodes.miniaturepets.MiniaturePets.load(MiniaturePets.java:381)
at com.kirelcodes.miniaturepets.MiniaturePets.onEnable(MiniaturePets.java:185)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472)
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386)
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488)
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:897)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by SilkPenny** [comment]
Same error on every restart for us:
https://pastebin.com/ecHsw31f

**Comment by danielnaaman** [comment]
Hello, I got several reports about this issue, but I can't seem to recreate it myself. [Here](https://pastebin.com/SNB3GQGi) you can find the  full startup logs for a fresh server with the latest PaperMC build along with the latest Miniature Pets version.

Please tell me if updating solves your issues.

@SilkPenny @metalshark 

Note: This is assuming that both of you started facing those issues after updating Paper.

**Comment by metalshark** [comment]
Hi @danielnaaman, am using Miniature Pets 2.4.1 and the latest version of Paper, when you ask if updating solves the issue do you mean downgrading Paper, or is there a newer version of Miniature Pets to update to?

**Comment by danielnaaman** [comment]
> Hi @danielnaaman, am using Miniature Pets 2.4.1 and the latest version of Paper, when you ask if updating solves the issue do you mean downgrading Paper, or is there a newer version of Miniature Pets to update to?

It appears that it isn't the cause of the issue, do you have any idea when did it start? Was it just with the latest version of Miniature Pets?

**Comment by metalshark** [comment]
It’s been in the last week so am thinking the latest Paper combined with a
pre-existing plugin.

**Comment by metalshark** [comment]
I am thinking that Paper was a red herring here and it's actually due to a head's skin not being available on certain mpet files. Will investigate, here's another stack trace:

```
java.lang.NullPointerException
at com.kirelcodes.miniaturepets.utils.ItemStackUtils.getSkullFromURL(ItemStackUtils.java:119)
at com.kirelcodes.miniaturepets.loader.ItemLoader.loadItem(ItemLoader.java:126)
at com.kirelcodes.miniaturepets.loader.ItemLoader.<init>(ItemLoader.java:36)
at com.kirelcodes.miniaturepets.loader.files.PetFile.<init>(PetFile.java:29)
at com.kirelcodes.miniaturepets.loader.PetLoader.registerFromFile(PetLoader.java:84)
at com.kirelcodes.miniaturepets.loader.PetLoader.<init>(PetLoader.java:47)
at com.kirelcodes.miniaturepets.MiniaturePets.load(MiniaturePets.java:381)
at com.kirelcodes.miniaturepets.MiniaturePets.onEnable(MiniaturePets.java:185)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472)
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386)
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488)
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:900)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by metalshark** [comment]
@danielnaaman yup this is due to individual mpet files. This will take an age to identify the culprits (just moved a whole load out for a test boot and got fewer instances of that error and with none in the folder I don't get the error at all). Would it be possible to name and shame culprit's with an error log message (one per error) please?

**Comment by SilkPenny** [comment]
Can confirm the same start-up error on PaperMC #298.

**Comment by liorsl** [comment]
@metalshark I will make sure to associate errors on loading with the pet. Unfortunately I don't know when the next version will be out, so in the meantime you may send me your pets and I will tell you which have that problem.

**Comment by metalshark** [comment]
Thank you. Appreciate you need something reproducible to fix. When I can get it down to something smaller than “on a fully loaded server” will post it here.

**Comment by metalshark** [comment]
Hi @danielnaaman it's all working fine now (not a single erro). Am thinking there was something wrong with an external source. Will have to write a quick script to edit the .mpet files to use HTTPS and audit they are still referring to active URLs.
