### ISSUE TITLE
[Bug Report] MariaDB 

### ISSUE THREAD

**Issue by MaxWainer** [MiniaturePets/Issues#262]
# Bug Report

### Technical Information
- Server Software: java 11, debian 10, and Spigot 1.12.2
- Plugin Version: latest 2.5.8
- /mpet dump: https://pastebin.com/ApJ2xYdg

### General Information

**Bug Description**

After moving to mariadb (Version 10.3.27), whever player is joining plugin throws and error

**Instructions To Produce**
1. Move to MariaDB
2. Join srever

**Logs**
https://pastebin.com/3BgycNL3

**Visual Demonstration**
No any

**Comment by DanielNaaman** [comment]
Am I correct to assume this is handled with our developers through Discord?

**Comment by MaxWainer** [comment]
Yes, they also suggested me to open ticket here

**Comment by MaxWainer** [comment]
also, when player is joining, it's spams:
```
[19:24:44 WARN]: java.sql.SQLException: Field 'ID' doesn't have a default value
[19:24:44 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[19:24:44 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
[19:24:44 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[19:24:44 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[19:24:44 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[19:24:44 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
[19:24:44 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[19:24:44 WARN]:        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197)
[19:24:44 WARN]:        at com.kirelcodes.miniaturepets.data.adapters.MySQLDataManager.initPlayer0(MySQLDataManager.java:52)
[19:24:44 WARN]:        at com.kirelcodes.miniaturepets.data.adapters.AsyncDataManager.lambda$initPlayer$0(AsyncDataManager.java:13)
[19:24:44 WARN]:        at com.kirelcodes.miniaturepets.data.adapters.AbstractDataManager.lambda$completeVoid$2(AbstractDataManager.java:59)
[19:24:44 WARN]:        at com.kirelcodes.miniaturepets.data.adapters.AbstractDataManager.async(AbstractDataManager.java:92)
[19:24:44 WARN]:        at com.kirelcodes.miniaturepets.data.adapters.AbstractDataManager.completeVoid(AbstractDataManager.java:57)
[19:24:44 WARN]:        at com.kirelcodes.miniaturepets.data.adapters.AsyncDataManager.initPlayer(AsyncDataManager.java:13)
[19:24:44 WARN]:        at com.kirelcodes.miniaturepets.listeners.PlayerJoinListener$1.run(PlayerJoinListener.java:48)
[19:24:44 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[19:24:44 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[19:24:44 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[19:24:44 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[19:24:44 WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by DanielNaaman** [comment]
A fix to this issue has been implemented and will be released in the upcoming update. Please reopen should the issue persist since we were unable to recreate the issue and the fix is kind of a shot in the dark.

**Comment by liorsl** [comment]
Hello,
This issue indicates a problem with gathering the name / UUID of the player.
Try switching ``SaveWithUUID`` in config.yml. If that doesn't work please let us know if you are using a fork of paper / spigot.

**Comment by MaxWainer** [comment]
okay, ty, gonna try rn

**Comment by liorsl** [comment]
Hello,
Can you update please?

**Comment by MaxWainer** [comment]
Ah, sry, issue resolved
