### ISSUE TITLE
[Bug Report] Error on entering black listed world

### ISSUE THREAD

**Issue by Donkk0** [MiniaturePets/Issues#301]
# Bug Report
Error on entering black listed world

### Technical Information
* Server Software: Paper version git-Paper-184 (MC: 1.18.1)
* Plugin Version:  2.6.4
* Dump File: https://pastebin.com/9L2Qpda2

### General Information

**Bug Description**
When I spawn a pet in a white-listed world, name it, and then enter a blacklisted world, I get the error provided below.

When I come back to a white-listed world and use **/pet call** it says I have no pet. In the **/pet** menu I get the same from the GUI. Image provided below.

I'm not sure if the latter is intended behavior when coming back from a black listed world, but the error on entering surely is not.

**Instructions To Produce**
1. Summon a pet and name it (not sure if the naming is necessary)
2. Use CMI Warp command to teleport into a black-listed world
3. Error appears in log
4. Back in white-listed worlds it tells me I don't have a pet yet when use /pet call

**Logs**
[14:41:39 INFO]: Donkko issued server command: /warp Creative
[14:41:40 WARN]: [MiniaturePets] Task #2941588 for MiniaturePets v2.6.4 generated an exception
java.lang.NullPointerException: Cannot invoke "com.kirelcodes.miniaturepets.pets.PetContainer.getModelEngineId()" because the return value of "com.kirelcodes.miniaturepets.pets.Pet.getContainer()" is null
        at com.kirelcodes.miniaturepets.pets.PetContainer.spawnPet(PetContainer.java:221) ~[MiniaturePets_v2.6.4-stable.jar:?]
        at com.kirelcodes.miniaturepets.listeners.PlayerChangedWorldListener.lambda$onPlayerChangeWorld$0(PlayerChangedWorldListener.java:36) ~[MiniaturePets_v2.6.4-stable.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-184]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-184]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-184]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-184]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-184]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-184]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-184]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Visual Demonstration**
https://cdn.discordapp.com/attachments/749361696824492124/940588487919423518/unknown.png

**Comment by DomiRusz24** [comment]
Hello, I am unable to re-produce the error message. I have used Multiverse teleport, (/mv tp) instead of CMI, as I don't have access to that plugin.

Upon entering a black listed world, the pet is removed from the world. So when you go back to a non-black listed world, it won't spawn back, you have to manually spawn it in again. So that is normal.

What are the names of both worlds? And are you sure there aren't any errors?

**Comment by Donkk0** [comment]
Hi! I have a couple of blacklisted worlds, I noticed this behavior when entering my Creative world, which is among the black listed ones. I didn't test with other black listed worlds. My white listed overworld is named Oleva, that's the place I entered the black listed world from.

No errors, just that warning.

Since the pet not respawning is intended behavior, I guess there's nothing out of the normal beyond that warning.

**Comment by DomiRusz24** [comment]
Are you able to reproduce the error with debug enabled? You should be able to find it in the config. Once you reproduce the error, please send the warning once again, including the debug messages.

**Comment by GC-spigot** [comment]
@Donkk0 Any new information?

**Comment by GC-spigot** [comment]
Fixed
