### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by DqnyLux** [MiniaturePets/Issues#318]
[00:25:40] [Server thread/INFO]: [MiniaturePets] Enabling MiniaturePets v2.7.4
[00:25:41] [Server thread/INFO]: [MiniaturePets] Loading reflections.
[00:25:41] [Server thread/WARN]: java.lang.NoSuchFieldException: a
[00:25:41] [Server thread/WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2549)
[00:25:41] [Server thread/WARN]:        at com.kirelcodes.miniaturepets.annotation.reflection.ReflectionAnnotationHandler.handleReflectedField(ReflectionAnnotationHandler.java:169)
[00:25:41] [Server thread/WARN]:        at com.kirelcodes.miniaturepets.annotation.reflection.ReflectionAnnotationHandler.handleClass(ReflectionAnnotationHandler.java:45)
[00:25:41] [Server thread/WARN]:        at com.kirelcodes.miniaturepets.reflections.GlobalReflectionResolver.resolve(GlobalReflectionResolver.java:134)
[00:25:41] [Server thread/WARN]:        at com.kirelcodes.miniaturepets.MiniaturePets.setupReflections(MiniaturePets.java:261)
[00:25:41] [Server thread/WARN]:        at com.kirelcodes.miniaturepets.MiniaturePets.onEnable(MiniaturePets.java:107)
[00:25:41] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[00:25:41] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[00:25:41] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[00:25:41] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:492)
[00:25:41] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:406)
[00:25:41] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:554)
[00:25:41] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:257)
[00:25:41] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928)
[00:25:41] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273)
[00:25:41] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[00:25:41] [Server thread/ERROR]: [MiniaturePets] Error loading global reflections
[00:25:41] [Server thread/ERROR]: [MiniaturePets] Unable to load reflections.

**Comment by Aurillium** [comment]
(This should be fixed in the next release)
