### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by Silvestre06** [MiniaturePets/Issues#364]
# Bug Report
 
1. Technical Information
* Server Software: Purpur 1.20.4
* Plugin Version:  2.8.3

2. **Bug Description**
Every time a block is broken on the ground an error appears in the console, saying it is something about mcmmo, but I didn't find anything about mcmmo in the plugin itself to solve this problem, please help me.

3. **Latest**
https://mclo.gs/ZzV1MwP

**Comment by Silvestre06** [comment]
<html>
<body>

[16:18:03] [Server thread/ERROR]: Could not pass event BlockBreakEvent to AdvancedPets v2.8.3
--
1204 | java.lang.ClassCastException: class net.advancedplugins.pets.impl.utils.hooks.PluginHookInstance cannot be cast to class net.advancedplugins.pets.impl.utils.hooks.plugins.McMMOHook (net.advancedplugins.pets.impl.utils.hooks.PluginHookInstance and net.advancedplugins.pets.impl.utils.hooks.plugins.McMMOHook are in unnamed module of loader 'AdvancedPets-2.8.3.jar' @25abfb0a)
1205 | at net.advancedplugins.pets.impl.commons.effects.mechanics.triggers.internal.MiningTrigger.onBlockBreak(MiningTrigger.java:53) ~[AdvancedPets-2.8.3.jar:?]
1206 | at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1095.execute(Unknown Source) ~[?:?]
1207 | at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
1208 | at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2127]
1209 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
1210 | at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2127]
1211 | at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2127]
1212 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
1213 | at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:375) ~[?:?]
1214 | at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:334) ~[?:?]
1215 | at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:298) ~[?:?]
1216 | at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1923) ~[?:?]
1217 | at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
1218 | at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
1219 | at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
1220 | at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.4.jar:git-Purpur-2127]
1221 | at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
1222 | at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
1223 | at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1486) ~[purpur-1.20.4.jar:git-Purpur-2127]
1224 | at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[purpur-1.20.4.jar:git-Purpur-2127]
1225 | at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
1226 | at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1463) ~[purpur-1.20.4.jar:git-Purpur-2127]
1227 | at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1386) ~[purpur-1.20.4.jar:git-Purpur-2127]
1228 | at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
1229 | at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1364) ~[purpur-1.20.4.jar:git-Purpur-2127]
1230 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1254) ~[purpur-1.20.4.jar:git-Purpur-2127]
1231 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2127]
1232 | at java.lang.Thread.run(Thread.java:833) ~[?:?]


</body>
</html>
